import type { PuzzleDefinition } from "./GameDefinitions.ts";

/**
 * Akerun V3 scoring contract.
 *
 * The V1 catalog's parTime is the deterministic route baseline generated by
 * the mechanical audit, not a human wall-clock target. V3 expands that
 * baseline into a provisional observation-time reference until real-device
 * timing is collected. Keep this policy in one module so the browser and the
 * replay verifier cannot silently drift apart.
 */
export const AKERUN_SCORE_CONTRACT_VERSION = "V3" as const;
export const SCORE_TIME_REFERENCE_MULTIPLIER = 10;
export const SCORE_BASE = 7_600;
export const SCORE_DIFFICULTY_UNIT = 1_000;
export const SCORE_TIME_PER_SECOND = 5;
export const SCORE_TIME_BONUS_CAP = 500;
export const SCORE_TIME_PENALTY_CAP = 1_800;
export const SCORE_SPEED_THRESHOLD_SECONDS = 60;
export const SCORE_SPEED_BONUS_PER_SECOND = 32;
export const SCORE_DIAL_PER_STEP = 1.5;
export const SCORE_DIAL_BONUS_CAP = 600;
export const SCORE_DIAL_PENALTY_CAP = 900;
export const SCORE_FAULT_PENALTY = 500;
export const SCORE_CLEAN_FAULT_BONUS = 100;
export const SCORE_FALSE_GATE_PENALTY = 12;

export type AkerunScoreBreakdown = {
  readonly timeReferenceSeconds: number;
  readonly timePart: number;
  readonly speedPart: number;
  readonly dialPart: number;
  readonly difficultyPart: number;
  readonly faultPart: number;
  readonly falseGatePart: number;
  readonly score: number;
};

const finiteOr = (value: number | undefined, fallback: number) =>
  Number.isFinite(value) ? (value as number) : fallback;

const nonNegative = (value: number | undefined, fallback = 0) =>
  Math.max(0, finiteOr(value, fallback));

const nonNegativeInteger = (value: number | undefined, fallback = 0) =>
  Math.max(0, Math.round(nonNegative(value, fallback)));

const clamp = (value: number, minimum: number, maximum: number) =>
  Math.min(maximum, Math.max(minimum, value));

export const scoreTimeReferenceSeconds = (problem: PuzzleDefinition) =>
  Math.max(1, finiteOr(problem.parTime, 60) * SCORE_TIME_REFERENCE_MULTIPLIER);

export const scoreExcessDialSteps = (
  problem: PuzzleDefinition,
  totalDialSteps: number
) =>
  Math.max(
    0,
    nonNegativeInteger(totalDialSteps) -
      Math.max(0, Math.round(finiteOr(problem.parDialSteps, 600)))
  );

export const observationAccuracy = (
  avoidableFalseGateContacts: number,
  faultCount: number
) =>
  clamp(
    Math.round(
      100 -
        nonNegativeInteger(avoidableFalseGateContacts) * 4 -
        nonNegativeInteger(faultCount) * 8
    ),
    0,
    100
  );

export const getAkerunScoreBreakdown = (
  problem: PuzzleDefinition,
  elapsedTime: number,
  faultCount: number,
  totalDialSteps: number,
  avoidableFalseGateContacts: number
): AkerunScoreBreakdown => {
  const safeElapsedTime = nonNegative(elapsedTime);
  const safeFaultCount = nonNegativeInteger(faultCount);
  const safeTotalDialSteps = nonNegativeInteger(totalDialSteps);
  const safeFalseGateContacts = nonNegativeInteger(avoidableFalseGateContacts);
  const parFaults = nonNegative(problem.parFaults);
  const faultDelta = safeFaultCount - parFaults;
  const timeReferenceSeconds = scoreTimeReferenceSeconds(problem);
  const timePart = clamp(
    Math.round(
      (timeReferenceSeconds - safeElapsedTime) * SCORE_TIME_PER_SECOND
    ),
    -SCORE_TIME_PENALTY_CAP,
    SCORE_TIME_BONUS_CAP
  );
  const speedPart = Math.round(
    Math.max(0, SCORE_SPEED_THRESHOLD_SECONDS - safeElapsedTime) *
      SCORE_SPEED_BONUS_PER_SECOND
  );
  const dialPart = clamp(
    Math.round(
      (Math.max(0, finiteOr(problem.parDialSteps, 600)) - safeTotalDialSteps) *
        SCORE_DIAL_PER_STEP
    ),
    -SCORE_DIAL_PENALTY_CAP,
    SCORE_DIAL_BONUS_CAP
  );
  const difficultyPart = Math.round(
    finiteOr(problem.difficultyWeight, 1) * SCORE_DIFFICULTY_UNIT
  );
  // A clean run may beat a problem whose expected route includes recovery,
  // but the bonus is deliberately smaller than the penalty for an extra jam.
  const faultPart =
    faultDelta >= 0
      ? Math.round(faultDelta * SCORE_FAULT_PENALTY)
      : Math.round(faultDelta * SCORE_CLEAN_FAULT_BONUS);
  const falseGatePart = Math.round(
    safeFalseGateContacts * SCORE_FALSE_GATE_PENALTY
  );
  const score = Math.max(
    0,
    SCORE_BASE +
      difficultyPart +
      timePart +
      speedPart +
      dialPart -
      faultPart -
      falseGatePart
  );
  return {
    timeReferenceSeconds,
    timePart,
    speedPart,
    dialPart,
    difficultyPart,
    faultPart,
    falseGatePart,
    score,
  };
};

export const calculateAkerunScore = (
  problem: PuzzleDefinition,
  elapsedTime: number,
  faultCount: number,
  totalDialSteps: number,
  avoidableFalseGateContacts: number
) =>
  getAkerunScoreBreakdown(
    problem,
    elapsedTime,
    faultCount,
    totalDialSteps,
    avoidableFalseGateContacts
  ).score;
